### ISSUE TITLE
Is ST7789V2 supported?

### ISSUE THREAD

**Issue by cretaceous-creature** [libdriver/st7789#2]
### Please ask your question

I'm using a 240x240 tft with ST7789V2 IC.  
The code is running but only noise on the screen, it seems the show and clear function works, I'm wondering if it is the IC version issue.

**Comment by libdriver** [comment]
This driver supports the V2 version of ST7789. The default resolution for the example or test is 240x320. If you use the 240x240 resolution, you need to modify the screen parameter configuration.

**Comment by cretaceous-creature** [comment]
thanks a lot, I bought another 7789, work now
